//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_SystemBI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Car_Rental_SystemBI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1054px_Dark_blue_right_arrow_svg__1_ {
            get {
                object obj = ResourceManager.GetObject("1054px-Dark_blue_right_arrow.svg (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1054px_Dark_blue_right_arrow1 {
            get {
                object obj = ResourceManager.GetObject("1054px-Dark_blue_right_arrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _162_1627009_right_clipart_blue_arrow_dark_blue_right_arrow {
            get {
                object obj = ResourceManager.GetObject("162-1627009_right-clipart-blue-arrow-dark-blue-right-arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2014_mazda_mazda6_rearview {
            get {
                object obj = ResourceManager.GetObject("2014_mazda_mazda6_rearview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2014_mazda_mazda6_rearview_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("2014_mazda_mazda6_rearview-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_Mazda_6___Side_132432_2560x1440_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("2017-Mazda-6---Side-132432-2560x1440-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_Mazda6_Sedan_Still__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("2017-Mazda6_Sedan_Still--removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _387332394_335089595737975_7927897251584690930_n {
            get {
                object obj = ResourceManager.GetObject("387332394_335089595737975_7927897251584690930_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _387332394_335089595737975_7927897251584690930_n___Copy {
            get {
                object obj = ResourceManager.GetObject("387332394_335089595737975_7927897251584690930_n - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _387332394_335089595737975_7927897251584690930_n_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("387332394_335089595737975_7927897251584690930_n-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _387332394_335089595737975_7927897251584690930_n_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("387332394_335089595737975_7927897251584690930_n-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _431482310_686263763494394_840724771521307803_n {
            get {
                object obj = ResourceManager.GetObject("431482310_686263763494394_840724771521307803_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _431482310_686263763494394_840724771521307803_n_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("431482310_686263763494394_840724771521307803_n-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _431482310_686263763494394_840724771521307803_n_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("431482310_686263763494394_840724771521307803_n-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _431482310_686263763494394_840724771521307803_n1 {
            get {
                object obj = ResourceManager.GetObject("431482310_686263763494394_840724771521307803_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _431482310_686263763494394_840724771521307803_n2 {
            get {
                object obj = ResourceManager.GetObject("431482310_686263763494394_840724771521307803_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _437965516_1500033357586218_7379727499865416264_n {
            get {
                object obj = ResourceManager.GetObject("437965516_1500033357586218_7379727499865416264_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _437965516_1500033357586218_7379727499865416264_n_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("437965516_1500033357586218_7379727499865416264_n-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438060502_1220960432203801_1598344734107430453_n {
            get {
                object obj = ResourceManager.GetObject("438060502_1220960432203801_1598344734107430453_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438060502_1220960432203801_1598344734107430453_n1 {
            get {
                object obj = ResourceManager.GetObject("438060502_1220960432203801_1598344734107430453_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438083572_1143697050211397_8501486425187951724_n {
            get {
                object obj = ResourceManager.GetObject("438083572_1143697050211397_8501486425187951724_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438083572_1143697050211397_8501486425187951724_n1 {
            get {
                object obj = ResourceManager.GetObject("438083572_1143697050211397_8501486425187951724_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438158177_7548567075189691_958771089205078046_n {
            get {
                object obj = ResourceManager.GetObject("438158177_7548567075189691_958771089205078046_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438158177_7548567075189691_958771089205078046_n_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("438158177_7548567075189691_958771089205078046_n-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438158177_7548567075189691_958771089205078046_n1 {
            get {
                object obj = ResourceManager.GetObject("438158177_7548567075189691_958771089205078046_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438196128_417439437588356_3539777731839527408_n {
            get {
                object obj = ResourceManager.GetObject("438196128_417439437588356_3539777731839527408_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438196128_417439437588356_3539777731839527408_n_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("438196128_417439437588356_3539777731839527408_n-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438196405_696524122485827_1933088196011884340_n {
            get {
                object obj = ResourceManager.GetObject("438196405_696524122485827_1933088196011884340_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438196405_696524122485827_1933088196011884340_n1 {
            get {
                object obj = ResourceManager.GetObject("438196405_696524122485827_1933088196011884340_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438203830_1144324686605815_7010408529047988058_n {
            get {
                object obj = ResourceManager.GetObject("438203830_1144324686605815_7010408529047988058_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438204088_3619067565023309_6094626311826266739_n {
            get {
                object obj = ResourceManager.GetObject("438204088_3619067565023309_6094626311826266739_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438204088_3619067565023309_6094626311826266739_n_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("438204088_3619067565023309_6094626311826266739_n-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438204088_3619067565023309_6094626311826266739_n_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("438204088_3619067565023309_6094626311826266739_n-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438204088_3619067565023309_6094626311826266739_n_removebg_preview__1_1 {
            get {
                object obj = ResourceManager.GetObject("438204088_3619067565023309_6094626311826266739_n-removebg-preview (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438204088_3619067565023309_6094626311826266739_n1 {
            get {
                object obj = ResourceManager.GetObject("438204088_3619067565023309_6094626311826266739_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438204088_3619067565023309_6094626311826266739_n2 {
            get {
                object obj = ResourceManager.GetObject("438204088_3619067565023309_6094626311826266739_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438204618_439417921942473_3173901310237888677_n {
            get {
                object obj = ResourceManager.GetObject("438204618_439417921942473_3173901310237888677_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438204618_439417921942473_3173901310237888677_n_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("438204618_439417921942473_3173901310237888677_n-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438209249_1520396381858061_2228830478514465266_n {
            get {
                object obj = ResourceManager.GetObject("438209249_1520396381858061_2228830478514465266_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438209249_1520396381858061_2228830478514465266_n_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("438209249_1520396381858061_2228830478514465266_n-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438221058_1382327879147110_3406138574498984307_n {
            get {
                object obj = ResourceManager.GetObject("438221058_1382327879147110_3406138574498984307_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438221058_1382327879147110_3406138574498984307_n1 {
            get {
                object obj = ResourceManager.GetObject("438221058_1382327879147110_3406138574498984307_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438221058_1382327879147110_3406138574498984307_n2 {
            get {
                object obj = ResourceManager.GetObject("438221058_1382327879147110_3406138574498984307_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438221058_1382327879147110_3406138574498984307_n3 {
            get {
                object obj = ResourceManager.GetObject("438221058_1382327879147110_3406138574498984307_n3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438223425_2193737374320196_4816848588470811706_n {
            get {
                object obj = ResourceManager.GetObject("438223425_2193737374320196_4816848588470811706_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438223425_2193737374320196_4816848588470811706_n_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("438223425_2193737374320196_4816848588470811706_n-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438223425_2193737374320196_4816848588470811706_n_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("438223425_2193737374320196_4816848588470811706_n-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438223425_2193737374320196_4816848588470811706_n1 {
            get {
                object obj = ResourceManager.GetObject("438223425_2193737374320196_4816848588470811706_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438223425_2193737374320196_4816848588470811706_n2 {
            get {
                object obj = ResourceManager.GetObject("438223425_2193737374320196_4816848588470811706_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438231708_1820650341765132_4869550420721421597_n_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("438231708_1820650341765132_4869550420721421597_n-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438231708_1820650341765132_4869550420721421597_n_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("438231708_1820650341765132_4869550420721421597_n-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438267501_1108825270366629_4210150369077201000_n {
            get {
                object obj = ResourceManager.GetObject("438267501_1108825270366629_4210150369077201000_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438267501_1108825270366629_4210150369077201000_n_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("438267501_1108825270366629_4210150369077201000_n-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438267501_1108825270366629_4210150369077201000_n1 {
            get {
                object obj = ResourceManager.GetObject("438267501_1108825270366629_4210150369077201000_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _438903098_287059621116011_1725405700825199326_n {
            get {
                object obj = ResourceManager.GetObject("438903098_287059621116011_1725405700825199326_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _439967638_395502853377452_4131224705706091645_n {
            get {
                object obj = ResourceManager.GetObject("439967638_395502853377452_4131224705706091645_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _439979236_1575548283295629_7050012137844077318_n {
            get {
                object obj = ResourceManager.GetObject("439979236_1575548283295629_7050012137844077318_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _439979236_1575548283295629_7050012137844077318_n1 {
            get {
                object obj = ResourceManager.GetObject("439979236_1575548283295629_7050012137844077318_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _439979236_1575548283295629_7050012137844077318_n2 {
            get {
                object obj = ResourceManager.GetObject("439979236_1575548283295629_7050012137844077318_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _440156707_409830208575985_2016248704654469787_n__1_ {
            get {
                object obj = ResourceManager.GetObject("440156707_409830208575985_2016248704654469787_n (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a65e3e47fb16e6309b925a79244d6174x_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("a65e3e47fb16e6309b925a79244d6174x-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a65e3e47fb16e6309b925a79244d6174x_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("a65e3e47fb16e6309b925a79244d6174x-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right_circle_icon_1024x1024_vd5nvvdh {
            get {
                object obj = ResourceManager.GetObject("arrow-right-circle-icon-1024x1024-vd5nvvdh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right_circle_icon_1024x1024_vd5nvvdh1 {
            get {
                object obj = ResourceManager.GetObject("arrow-right-circle-icon-1024x1024-vd5nvvdh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrows_back_forward {
            get {
                object obj = ResourceManager.GetObject("arrows_back_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Desktop_cars_full_hd_wallpapers_1080p_download {
            get {
                object obj = ResourceManager.GetObject("Desktop-cars-full-hd-wallpapers-1080p-download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap g_cvt_orange_metallic_3_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("g-cvt-orange-metallic-3-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap peso {
            get {
                object obj = ResourceManager.GetObject("peso", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap peso_sign {
            get {
                object obj = ResourceManager.GetObject("peso-sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap raize_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("raize-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap raize_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("raize-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__116_ {
            get {
                object obj = ResourceManager.GetObject("Screenshot (116)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__116_1 {
            get {
                object obj = ResourceManager.GetObject("Screenshot (116)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__118_ {
            get {
                object obj = ResourceManager.GetObject("Screenshot (118)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__119_ {
            get {
                object obj = ResourceManager.GetObject("Screenshot (119)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__120_ {
            get {
                object obj = ResourceManager.GetObject("Screenshot (120)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__121_ {
            get {
                object obj = ResourceManager.GetObject("Screenshot (121)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__121_1 {
            get {
                object obj = ResourceManager.GetObject("Screenshot (121)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__122_ {
            get {
                object obj = ResourceManager.GetObject("Screenshot (122)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__123__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Screenshot__123_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_04_28_224652 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-04-28 224652", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_04_28_224919 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2024-04-28 224919", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_05_20_231920_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2024-05-20_231920-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_05_20_235927_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2024-05-20_235927-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_05_20_235927_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2024-05-20_235927-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
